// src/app/transactions/deposit-withdraw/page.tsx
"use client";

import React, { useState, useEffect } from 'react';
import { Banknote, ArrowUpRight, ArrowDownLeft } from 'lucide-react';
import { Account } from '@/lib/types';
import { getStoredAccounts, saveAccounts } from '@/lib/store';
import { StatusMessage } from '@/components/StatusMessage';

export default function DepositWithdrawPage() {
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [message, setMessage] = useState('');
  
  const [formData, setFormData] = useState({
    company: 'MOD-CORP-01',
    accNo: '',
    sign: '+' as '+' | '-',
    amt: '100.00',
    sortCode: '10-20-30'
  });

  useEffect(() => {
    const accs = getStoredAccounts();
    setAccounts(accs);
    if (accs.length > 0) {
      setFormData(prev => ({ ...prev, accNo: accs[0].accNo, sortCode: accs[0].srtCd }));
    }
    setMessage('BNK1CDM - DEPOSIT & WITHDRAWAL ROUTINE ACTIVE');
  }, []);

  const selectedAccount = accounts.find(a => a.accNo === formData.accNo);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const amount = parseFloat(formData.amt);
    if (isNaN(amount) || amount <= 0) {
      setMessage('BNK1CDM ERROR: AMOUNT MUST BE A POSITIVE NUMBER.');
      return;
    }

    if (!selectedAccount) {
      setMessage('BNK1CDM ERROR: VALID ACCOUNT MUST BE SELECTED.');
      return;
    }

    if (formData.sign === '-' && (selectedAccount.avail + selectedAccount.overdr) < amount) {
      setMessage(`BNK1CDM REJECTED: INSUFFICIENT FUNDS IN ${selectedAccount.accNo}. AVAIL + OVERDRAFT EXCEEDED.`);
      return;
    }

    const delta = formData.sign === '+' ? amount : -amount;
    const updatedAccounts = accounts.map(a => {
      if (a.accNo === formData.accNo) {
        return {
          ...a,
          avail: a.avail + delta,
          actBal: a.actBal + delta,
          lastMessage: `BNK1CDM ${formData.sign === '+' ? 'DEPOSIT' : 'WITHDRAWAL'} OF $${amount.toFixed(2)} COMPLETED`
        };
      }
      return a;
    });

    setAccounts(updatedAccounts);
    saveAccounts(updatedAccounts);
    setMessage(`BNK1CDM SUCCESS: ${formData.sign === '+' ? 'DEPOSITED' : 'WITHDREW'} $${amount.toFixed(2)} ON ${formData.accNo}. NEW AVAIL BAL: $${(selectedAccount.avail + delta).toFixed(2)}`);
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto font-mono text-xs">
      <div className="border-b border-slate-800 pb-4">
        <h2 className="text-2xl font-bold text-white flex items-center gap-2">
          <Banknote className="w-6 h-6 text-sky-400" /> Cash Transaction Processing
        </h2>
        <p className="text-slate-400 text-[11px] mt-1">
          Legacy BMS Map: BNK1CDM (Account Cash Deposit / Withdrawal)
        </p>
      </div>

      <StatusMessage message={message} mapset="BNK1CDM" />

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <form onSubmit={handleSubmit} className="md:col-span-2 bg-slate-900 border border-slate-800 rounded-lg p-6 space-y-6 shadow-xl">
          <div className="border-b border-slate-800 pb-2 text-sky-400 font-bold uppercase text-[11px]">
            BMS Field Inputs (BNK1CDM)
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-slate-400 mb-1">COMPANY</label>
              <input
                type="text"
                value={formData.company}
                onChange={e => setFormData({ ...formData, company: e.target.value })}
                className="w-full bg-slate-950 border border-slate-700 rounded px-3 py-2 text-white outline-none focus:border-sky-500"
              />
            </div>
            <div>
              <label className="block text-slate-400 mb-1">SORT CODE (SORTC)</label>
              <input
                type="text"
                value={formData.sortCode}
                onChange={e => setFormData({ ...formData, sortCode: e.target.value })}
                className="w-full bg-slate-950 border border-slate-700 rounded px-3 py-2 text-white outline-none focus:border-sky-500"
              />
            </div>
          </div>

          <div>
            <label className="block text-slate-400 mb-1">TARGET ACCOUNT (ACCNO)</label>
            <select
              value={formData.accNo}
              onChange={e => {
                const acc = accounts.find(a => a.accNo === e.target.value);
                setFormData({ ...formData, accNo: e.target.value, sortCode: acc?.srtCd || formData.sortCode });
              }}
              className="w-full bg-slate-950 border border-slate-700 rounded px-3 py-2 text-sky-400 font-bold outline-none focus:border-sky-500"
            >
              {accounts.map(a => (
                <option key={a.accNo} value={a.accNo}>
                  {a.accNo} - {a.accTyp} (Bal: ${a.avail.toFixed(2)})
                </option>
              ))}
            </select>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-slate-400 mb-1">TRANSACTION SIGN (SIGN)</label>
              <div className="flex items-center space-x-2">
                <button
                  type="button"
                  onClick={() => setFormData({ ...formData, sign: '+' })}
                  className={`flex-1 py-2 rounded font-bold border transition-colors flex items-center justify-center gap-1 ${
                    formData.sign === '+' 
                      ? 'bg-emerald-950 border-emerald-500 text-emerald-400'
                      : 'bg-slate-950 border-slate-800 text-slate-500'
                  }`}
                >
                  <ArrowDownLeft className="w-4 h-4" /> + Deposit
                </button>
                <button
                  type="button"
                  onClick={() => setFormData({ ...formData, sign: '-' })}
                  className={`flex-1 py-2 rounded font-bold border transition-colors flex items-center justify-center gap-1 ${
                    formData.sign === '-' 
                      ? 'bg-red-950 border-red-500 text-red-400'
                      : 'bg-slate-950 border-slate-800 text-slate-500'
                  }`}
                >
                  <ArrowUpRight className="w-4 h-4" /> - Withdrawal
                </button>
              </div>
            </div>
            <div>
              <label className="block text-slate-400 mb-1">AMOUNT (AMT)</label>
              <input
                type="number"
                step="0.01"
                value={formData.amt}
                onChange={e => setFormData({ ...formData, amt: e.target.value })}
                className="w-full bg-slate-950 border border-slate-700 rounded px-3 py-2 text-emerald-400 font-bold text-base outline-none focus:border-sky-500"
              />
            </div>
          </div>

          <button
            type="submit"
            className="w-full bg-sky-600 hover:bg-sky-500 text-white font-mono text-xs py-3 rounded transition-colors font-bold uppercase shadow-md"
          >
            EXECUTE TRANSACTION (BNK1CDM)
          </button>
        </form>

        {/* Account Detail Box */}
        <div className="bg-slate-900 border border-slate-800 rounded-lg p-5 space-y-4 shadow-xl flex flex-col justify-between">
          <div>
            <h3 className="text-xs font-bold text-slate-300 uppercase border-b border-slate-800 pb-2 mb-3">
              Current Ledger Record
            </h3>
            {selectedAccount ? (
              <div className="space-y-3">
                <div>
                  <span className="text-slate-500 block text-[10px]">ACCOUNT NUMBER</span>
                  <span className="text-sky-400 font-bold text-sm">{selectedAccount.accNo}</span>
                </div>
                <div>
                  <span className="text-slate-500 block text-[10px]">CUSTOMER REF</span>
                  <span className="text-slate-200 font-bold">{selectedAccount.custNo}</span>
                </div>
                <div>
                  <span className="text-slate-500 block text-[10px]">SORT CODE</span>
                  <span className="text-slate-200 font-bold">{selectedAccount.srtCd}</span>
                </div>
                <div>
                  <span className="text-slate-500 block text-[10px]">AVAILABLE BALANCE (AVBAL)</span>
                  <span className="text-emerald-400 font-bold text-lg">${selectedAccount.avail.toFixed(2)}</span>
                </div>
                <div>
                  <span className="text-slate-500 block text-[10px]">ACTUAL BALANCE (ACTBAL)</span>
                  <span className="text-slate-100 font-bold text-sm">${selectedAccount.actBal.toFixed(2)}</span>
                </div>
              </div>
            ) : (
              <p className="text-slate-500 text-center py-6">No account selected</p>
            )}
          </div>
          <div className="text-[10px] text-slate-500 border-t border-slate-800 pt-3 font-mono">
            COBOL Record: BNK1CDM-REC
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend/src/app/components/deposit-withdraw/deposit-withdraw.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule, CurrencyPipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { CrmService } from '../../services/crm.service';
import { Account, CRMOperationResult } from '../../models/crm-models';

@Component({
  selector: 'app-deposit-withdraw',
  standalone: true,
  imports: [CommonModule, FormsModule, CurrencyPipe],
  template: `
    <div class="max-w-2xl mx-auto space-y-6">
      <div class="border-b border-slate-800 pb-4">
        <h1 class="text-2xl font-bold text-white">Deposit & Debit Management</h1>
        <p class="text-slate-400 text-sm mt-1">COBOL BMS Map: BNK1CDM (ACCNO, SIGN, AMT, SORTC, AVBAL, ACTBAL)</p>
      </div>

      @if (result) {
        <div [class]="result.success ? 'p-4 rounded-lg bg-emerald-950/80 border border-emerald-600 text-emerald-200' : 'p-4 rounded-lg bg-rose-950/80 border border-rose-600 text-rose-200'">
          <p class="font-bold text-base">{{ result.success ? 'Transaction Processed' : 'Transaction Failed' }}</p>
          <p class="text-sm mt-1">{{ result.message }}</p>
          <p class="text-xs opacity-75 mt-2 font-mono">Timestamp: {{ result.timestamp }}</p>
        </div>
      }

      <form (ngSubmit)="executeTransaction()" #txForm="ngForm" class="glass-card p-6 space-y-6">
        <div>
          <label class="block text-xs font-semibold uppercase text-slate-400 mb-1">Select Target Account (ACCNO)</label>
          <select [(ngModel)]="selectedAccNo" (ngModelChange)="onAccountSelect()" name="selectedAccNo" required class="input-field font-mono">
            @for (acc of accounts; track acc.accountNumber) {
              <option [value]="acc.accountNumber">{{ acc.accountNumber }} (Sort: {{ acc.sortCode }}) - Balance: {{ acc.actualBalance | currency }}</option>
            }
          </select>
        </div>

        @if (currentAccount) {
          <div class="p-4 rounded-lg bg-slate-800/80 border border-slate-700 grid grid-cols-2 gap-4 text-sm font-mono">
            <div>
              <span class="text-slate-400 text-xs block">Available Balance (AVBAL):</span>
              <span class="text-white font-bold text-lg">{{ currentAccount.availableBalance | currency }}</span>
            </div>
            <div>
              <span class="text-slate-400 text-xs block">Actual Balance (ACTBAL):</span>
              <span class="text-emerald-400 font-bold text-lg">{{ currentAccount.actualBalance | currency }}</span>
            </div>
          </div>
        }

        <div>
          <label class="block text-xs font-semibold uppercase text-slate-400 mb-1">Transaction Action (SIGN)</label>
          <div class="grid grid-cols-2 gap-4">
            <button 
              type="button" 
              (click)="sign = '+'" 
              [class]="sign === '+' ? 'btn-primary border-2 border-emerald-400 bg-emerald-600 hover:bg-emerald-500' : 'btn-secondary'"
            >
              + Deposit
            </button>
            <button 
              type="button" 
              (click)="sign = '-'" 
              [class]="sign === '-' ? 'btn-danger border-2 border-rose-400' : 'btn-secondary'"
            >
              - Debit / Withdrawal
            </button>
          </div>
        </div>

        <div>
          <label class="block text-xs font-semibold uppercase text-slate-400 mb-1">Transaction Amount (AMT)</label>
          <input 
            type="number" 
            step="0.01" 
            min="0.01" 
            [(ngModel)]="amount" 
            name="amount" 
            required 
            placeholder="0.00" 
            class="input-field text-xl font-mono text-emerald-400"
          />
        </div>

        <button 
          type="submit" 
          [disabled]="!txForm.form.valid || amount <= 0" 
          class="w-full btn-primary py-3 text-lg font-bold shadow-lg"
        >
          Process {{ sign === '+' ? 'Deposit' : 'Debit' }} Operation
        </button>
      </form>
    </div>
  `
})
export class DepositWithdrawComponent implements OnInit {
  accounts: Account[] = [];
  selectedAccNo = '';
  currentAccount?: Account;
  sign: '+' | '-' = '+';
  amount: number = 0;
  result?: CRMOperationResult;

  constructor(private crmService: CrmService) {}

  ngOnInit(): void {
    this.crmService.getAccounts().subscribe(accs => {
      this.accounts = accs;
      if (accs.length > 0 && !this.selectedAccNo) {
        this.selectedAccNo = accs[0].accountNumber;
        this.onAccountSelect();
      }
    });
  }

  onAccountSelect(): void {
    this.currentAccount = this.accounts.find(a => a.accountNumber === this.selectedAccNo);
  }

  executeTransaction(): void {
    if (!this.currentAccount) return;

    this.crmService.executeDepositWithdraw({
      company: this.currentAccount.company,
      accountNumber: this.currentAccount.accountNumber,
      sortCode: this.currentAccount.sortCode,
      sign: this.sign,
      amount: this.amount
    }).subscribe(res => {
      this.result = res;
      if (res.success) {
        this.amount = 0;
        this.onAccountSelect();
      }
    });
  }
}
